[package]
name = "rpc-proxy"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
cli = { path = "../cli" }
env_logger = "0.5"
proxy = { path = "../proxy" }
tokio-core = "0.1"
transports = { path = "../transports" }
